apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: harbor.bar.kube-plus.cloud/hackathon/hello-world:v2
          ports:
            - containerPort: 8080